### ISSUE TITLE
Analysisd crashes when using snort-full

### ISSUE THREAD

**Issue by ddpbsd** [ossec/ossec-hids#1018]
ossec-analysisd has been crashing for me since I added a snort-full localfile with a server from MASTER.
I have not tested with 2.8.x or 2.9, and I have not looked into it much.

Trace:
```
2016/12/29 13:39:16 ossec-analysisd: DEBUG: Startup completed. Waiting for new messages..

Program received signal SIGSEGV, Segmentation fault.
0x000014d664c3edb1 in _OS_Regex (pattern=0x14d944913d00 "\\\n+ \\\n+ \\\n+ [\\\n+ \\\n\\\001+] \"\\\002+ \\\n+ http\\\n+\" ", str=0x14d9354ebff1 "", prts_closure=0x0, prts_str=0x0, flags=128) at os_regex/os_regex_execute.c:368
368         } while (*(++st) != '\0');
(gdb) bt
#0  0x000014d664c3edb1 in _OS_Regex (pattern=0x14d944913d00 "\\\n+ \\\n+ \\\n+ [\\\n+ \\\n\\\001+] \"\\\002+ \\\n+ http\\\n+\" ", str=0x14d9354ebff1 "", prts_closure=0x0, prts_str=0x0, flags=128) at os_regex/os_regex_execute.c:368
#1  0x000014d664c3e627 in OSRegex_Execute (str=0x14d9354ebff1 "", reg=0x14d91a735480) at os_regex/os_regex_execute.c:86
#2  0x000014d664c1c0b9 in DecodeEvent (lf=0x14d90485ee00) at analysisd/decoders/decoder.c:55
#3  0x000014d664c108b8 in OS_ReadMSG (m_queue=17) at analysisd/analysisd.c:797
#4  0x000014d664c10142 in main (argc=2, argv=0x7f7ffffce878) at analysisd/analysisd.c:532
```

Agent config:
```
  <localfile>
    <log_format>snort-full</log_format>
    <location>/var/snort/log/alert</location>
  </localfile>
```

**Comment by atomicturtle** [comment]
Ive had this running on 2.9RCx with snort-full for months. I'll retest that with master to see if I can duplicate the crash. How long does it take to fail on yours?

**Comment by ddpbsd** [comment]
As soon as it gets a log, I think.
